# SPDX-FileCopyrightText: Copyright (C) 2025 Julien M. (dev[at]ingeoveritas[dot]com) and Contributors to the project (https://github.com/MartenBE/mkslides/graphs/contributors)
#
# SPDX-License-Identifier: MIT
---
changelog:
  categories:
    - title: Bug fixes 🐛
      labels:
        - bug
    - title: Features and enhancements 🎉
      labels:
        - enhancement
    - title: Tooling 🔧
      labels:
        - Dependencies
        - github_actions
    - title: Documentation 📖
      labels:
        - documentation
    - title: Other changes
      labels:
        - "*"
