# SPDX-FileCopyrightText: Copyright (C) 2026 Martijn Saelens and Contributors to the project (https://github.com/MartenBE/mkslides/graphs/contributors)
#
# SPDX-License-Identifier: MIT
---
extends: default

rules:
  line-length: disable
  comments:
    min-spaces-from-content: 1
