on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - run: pip install poetry
      - run: poetry install --with dev
      - run: poetry run ruff format --check
      # - run: poetry run ruff check # TODO: Enable this line
      # - run: poetry run mypy src/ tests/  # TODO: Enable this line
      - run: poetry run pytest
